apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      volumes:
        - name: local-repo
          hostPath:
            path: /opt/octonaut
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - mountPath: /opt/octonaut
              name: local-repo
