apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  project: default

  source:
    repoURL: https://github.com/kubernetes/kube-state-metrics.git
    path: examples/standard
    targetRevision: main

  destination:
    name: in-cluster
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
